source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'SAVideoPlayer_Example' do
  pod 'SAVideoPlayer', :path => '../'
  
  target 'SAVideoPlayer_Tests' do
      inherit! :search_paths
  end
end
